#ifndef CONSTANTS_H
#define CONSTANTS_H

const int ELEVATOR_STATE_IDLE = 0;
const int ELEVATOR_STATE_GOING_DOWN = 1;
const int ELEVATOR_STATE_GOING_UP = 2;
const int ELEVATOR_STATE_READJUSTING = 3;
const int ELEVATOR_STATE_STOPPED = 4;

const int ELEVATOR_HEIGHT = 5;
const int ELEVATOR_WIDTH = 5;

const int FLOOR_WIDTH = 6;
const int FLOOR_HEIGHT = 10;

const int TICKS_TO_STOP = 5;

const int TICKS_PASSENGER_SPAWN_INTERVAL = 10;
#endif